# Generated by Django 5.2.6 on 2025-10-25 02:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la catégorie')),
                ('type_categorie', models.CharField(choices=[('depense', 'Dépense'), ('revenu', 'Revenu')], max_length=10, verbose_name='Type')),
                ('icone', models.CharField(blank=True, help_text="Nom de l'icône (ex: health, education, travel)", max_length=50, null=True)),
                ('couleur', models.CharField(default='#3B82F6', help_text='Code couleur hexadécimal (ex: #3B82F6)', max_length=7)),
                ('est_predefinite', models.BooleanField(default=False, help_text='Les catégories prédéfinies sont proposées par défaut à tous les utilisateurs', verbose_name='Catégorie prédéfinie')),
                ('est_active', models.BooleanField(default=True, help_text='Désactiver une catégorie la cache sans la supprimer', verbose_name='Active')),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage (0 = en premier)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'db_table': 'transactions_categorie',
                'ordering': ['ordre', 'nom'],
                'unique_together': {('nom', 'type_categorie', 'creee_par')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID unique')),
                ('volet', models.CharField(choices=[('suivi', 'Suivi'), ('budget', 'Budget')], default='suivi', help_text="S'agit-il d'un suivi réel ou d'un budget prévisionnel ?", max_length=10, verbose_name='Volet')),
                ('position', models.CharField(choices=[('depense', 'Dépense'), ('revenu', 'Revenu')], help_text="S'agit-il d'une dépense ou d'un revenu ?", max_length=10, verbose_name='Position')),
                ('libelle', models.CharField(help_text='Description courte de la transaction', max_length=200, verbose_name='Libellé')),
                ('commentaire', models.TextField(blank=True, help_text='Notes ou détails supplémentaires', null=True, verbose_name='Commentaire')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant')),
                ('devise', models.CharField(default='XAF', max_length=3, verbose_name='Devise')),
                ('photo', models.ImageField(blank=True, help_text='Photo de la transaction ou du reçu', null=True, upload_to='transactions/%Y/%m/', verbose_name='Photo/Reçu')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('annulee', 'Annulée')], default='validee', max_length=20, verbose_name='Statut')),
                ('date', models.DateTimeField(verbose_name='Date de la transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifiée le')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='transactions.categorie', verbose_name='Catégorie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions_transaction',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='transaction_user_id_8af7f1_idx'), models.Index(fields=['user', 'volet', 'position'], name='transaction_user_id_e53dad_idx'), models.Index(fields=['categorie', 'date'], name='transaction_categor_c60a49_idx')],
            },
        ),
    ]
