# Generated by Django 5.2.6 on 2025-09-14 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('categorie', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(choices=[('revenu', 'Revenu'), ('depense', 'Dépense')], max_length=8)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
