# Generated by Django 5.2.6 on 2025-10-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_options_transaction_local_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='local_id',
            field=models.PositiveIntegerField(default=-1),
        ),
    ]
