# Generated by Django 5.2.6 on 2025-10-07 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_transaction_local_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['local_id']},
        ),
    ]
