# Generated by Django 5.2.6 on 2025-10-07 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_alter_transaction_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='local_id',
        ),
    ]
