# Generated by Django 5.2.6 on 2025-10-08 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_alter_transaction_options_transaction_local_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['user', 'local_id']},
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together=set(),
        ),
    ]
